system:
  port: 6789
  pre: api/services/app/
  tokenexpire: 36000
  token: owentoken
  debug: true
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0
mongodb:
  # uri: "mongodb://localhost:27017"
  uri:
  database: "testdb"
  username: "your_username"
  password: "your_password"

db:
  type: mysql
  mysql: "root:abc@123@tcp(127.0.0.1:3306)/invengodbv41?charset=utf8mb4&parseTime=True&loc=Local" # 数据库类型（mysql, postgres, sqlite, sqlserver, oracle）
  mssql: "server=192.168.8.75,1433;user id=sa;password=123456;database=owen"
  oracle: "user/password@localhost:1521/service_name"
  postgres: "user=postgres password=secret dbname=mydb host=127.0.0.1 port=5432 sslmode=disable"
  sqlite: "data.db"
  maxopenconns: 100
  maxidleconns: 10
  connmaxlifetime: 30
