system:
  port: 6789

db:
  type: mysql # 数据库类型（mysql, postgres, sqlite, sqlserver, oracle）
  url: "root:abc@123@tcp(127.0.0.1:3306)/invengodbv41?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  url: 127.0.0.1:6379,password=002161
  db: 0
mongodb:
  url:





# 如果是 PostgreSQL
# db:
#   type: postgres
#   url: "user=postgres password=secret dbname=mydb host=127.0.0.1 port=5432 sslmode=disable"

# 如果是 SQLite
# db:
#   type: sqlite
#   url: "data.db"

# 如果是 SQL Server
# db:
#   type: sqlserver
#   url: "server=192.168.8.75,1433;user id=sa;password=123456;database=owen"

# 如果是 Oracle
# db:
#   type: oracle
#   url: "user/password@localhost:1521/xe"
