system:
  port: 6789
  routerpre: api/services/app/
  tokenexpire: 24 #hour
  token: Token
  enabledebug: false
  blacklistpre: owen_
  enableblacklist: true
  ipwhitelist: ::1,localhost,127.0.0.1
  swaggerui: true #是否开启swagger
  enablewebsocket: true
  taskinterval: 60 #任务检查时间 单位秒
  taskdb: redis #默认使用数据库
  taskpre: owen_ #redis前缀

  circuitbreaker:
    maxrequests: 20 #20个请求 最大请求数
    second: 10 #10秒  监控时间窗口（秒）
    addblacklistminutes: 0 #超过这个阈值增加到黑名单中 分钟 0则不生效
  ratelimiter:
    ratelimit: 10 #每秒多少个请求 每秒请求数量
    burst: 20 #并发 最大并发数
    addblacklistminutes: 0 #超过这个阈值增加到黑名单中 分钟 0则不生效
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0
mongodb:
  # uri: "mongodb://localhost:27017"
  uri:
  database: "testdb"
  username: "your_username"
  password: "your_password"

db:
  default:
    type: mysql
    cancreatemodel: false #无效占位
    canautomigration: false #无效 占位符
    canautosyndata: false #无效 占位符
    mysql: "root:abc@123@tcp(127.0.0.1:3306)/invengodbv41?charset=utf8mb4&parseTime=True&loc=Local" # 数据库类型（mysql, postgres, sqlite, sqlserver, oracle）
    mssql: "server=192.168.8.75,1433;user id=sa;password=123456;database=testDB"
    oracle: "user/password@localhost:1521/service_name"
    postgres: "user=postgres password=secret dbname=mydb host=127.0.0.1 port=5432 sslmode=disable"
    sqlite: "invengo.db"
    maxopenconns: 100
    maxidleconns: 10
    connmaxlifetime: 30
  from:
    type: mysql #空则数据库不初始化
    cancreatemodel: false #是否允许from 数据库生成model文件
    canautomigration: true #是否允许from 数据库生成migration文件
    canautosyndata: true #是否允许from 数据库生成syncdata文件
    mysql: "root:abc@123@tcp(127.0.0.1:3306)/invengodbv41?charset=utf8mb4&parseTime=True&loc=Local" # 数据库类型（mysql, postgres, sqlite, sqlserver, oracle）
    mssql: "server=192.168.8.75,1433;user id=sa;password=123456;database=testDB"
    oracle: "user/password@localhost:1521/service_name"
    postgres: "user=postgres password=secret dbname=mydb host=127.0.0.1 port=5432 sslmode=disable"
    sqlite: "invengo.db"
    maxopenconns: 100
    maxidleconns: 10
    connmaxlifetime: 30
  to:
    type: sqlite #空则数据库不初始化
    cancreatemodel: false #无效占位
    canautomigration: false #是否根据from 生成表结构
    canautosyndata: false #是否通过from 生成表结构数据
    mysql: "root:abc@123@tcp(127.0.0.1:3306)/invengodbv41?charset=utf8mb4&parseTime=True&loc=Local" # 数据库类型（mysql, postgres, sqlite, sqlserver, oracle）
    mssql: "server=192.168.8.75,1433;user id=sa;password=123456;database=testDB"
    oracle: "user/password@localhost:1521/service_name"
    postgres: "user=postgres password=secret dbname=mydb host=127.0.0.1 port=5432 sslmode=disable"
    sqlite: "invengo.db"
    maxopenconns: 100
    maxidleconns: 10
    connmaxlifetime: 30
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  exchangename: topic_exchange #direct_exchange  fanout_exchange headers_exchange
  exchangetype: topic #direct fanout  headers

rabbitmqconsumer:
  url: amqp://guest:guest@localhost:5672/
  exchangename: topic_exchange #direct_exchange  fanout_exchange headers_exchange
  exchangetype: topic #direct fanout  headers
  queuename: server_queue
  #  *是精确匹配单个单词，用于更细粒度的控制。 default_routingKey.one  default_routingKey.two
  #  # 是更宽松的匹配规则，用于匹配零个或多个单词。  default_routingKey  default_routingKey.one  任何以 default_routingKey 开头的 routingKey 都匹配
  routingkey: default_routingKey.*
