system:
  port: 6789
  routerpre: api/services/app/
  tokenexpire: 24 #hour
  token: Token
  enabledebug: false
  blacklistpre: owen_
  enableblacklist: true
  ipwhitelist: ::1,localhost,127.0.0.1
  swaggerui: true #是否开启swagger
  enablewebsocket: true
  circuitbreaker:
    maxrequests: 20 #20个请求 最大请求数
    second: 10 #10秒  监控时间窗口（秒）
    addblacklistminutes: 0 #超过这个阈值增加到黑名单中 分钟 0则不生效
  ratelimiter:
    ratelimit: 10 #每秒多少个请求 每秒请求数量
    burst: 20 #并发 最大并发数
    addblacklistminutes: 0 #超过这个阈值增加到黑名单中 分钟 0则不生效
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0
mongodb:
  # uri: "mongodb://localhost:27017"
  uri:
  database: "testdb"
  username: "your_username"
  password: "your_password"

db:
  type: mysql
  mysql: "root:abc@123@tcp(127.0.0.1:3306)/invengodbv41?charset=utf8mb4&parseTime=True&loc=Local" # 数据库类型（mysql, postgres, sqlite, sqlserver, oracle）
  mssql: "server=192.168.8.75,1433;user id=sa;password=123456;database=owen"
  oracle: "user/password@localhost:1521/service_name"
  postgres: "user=postgres password=secret dbname=mydb host=127.0.0.1 port=5432 sslmode=disable"
  sqlite: "invengo.db"
  maxopenconns: 100
  maxidleconns: 10
  connmaxlifetime: 30

rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  exchangename: topic_exchange
  exchangetype: topic


rabbitmqconsumer:
  url: amqp://guest:guest@localhost:5672/
  exchangename: topic_exchange
  exchangetype: topic
  queuename: server_queue
  routingkey: default_routingKey.*

