// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthPermission = "auth_permission"

// AuthPermission mapped from table <auth_permission>
type AuthPermission struct {
	ID            int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name          string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	ContentTypeID int64  `gorm:"column:content_type_id;type:int;not null" json:"content_type_id"`
	Codename      string `gorm:"column:codename;type:varchar(100);not null" json:"codename"`
}

// TableName AuthPermission's table name
func (*AuthPermission) TableName() string {
	return TableNameAuthPermission
}
