// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHangfirecounter = "hangfirecounter"

// Hangfirecounter mapped from table <hangfirecounter>
type Hangfirecounter struct {
	ID       int64      `gorm:"column:Id;type:int;primaryKey;autoIncrement:true" json:"Id"`
	Key      string     `gorm:"column:Key;type:varchar(100);not null" json:"Key"`
	Value    int64      `gorm:"column:Value;type:int;not null" json:"Value"`
	ExpireAt *time.Time `gorm:"column:ExpireAt;type:datetime" json:"ExpireAt"`
}

// TableName Hangfirecounter's table name
func (*Hangfirecounter) TableName() string {
	return TableNameHangfirecounter
}
