// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysDataAuthorityID = "sys_data_authority_id"

// SysDataAuthorityID mapped from table <sys_data_authority_id>
type SysDataAuthorityID struct {
	SysAuthorityAuthorityID    int64 `gorm:"column:sys_authority_authority_id;type:bigint unsigned;primaryKey" json:"sys_authority_authority_id"`         // 角色ID
	DataAuthorityIDAuthorityID int64 `gorm:"column:data_authority_id_authority_id;type:bigint unsigned;primaryKey" json:"data_authority_id_authority_id"` // 角色ID
}

// TableName SysDataAuthorityID's table name
func (*SysDataAuthorityID) TableName() string {
	return TableNameSysDataAuthorityID
}
