// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysBaseMenuParameter = "sys_base_menu_parameters"

// SysBaseMenuParameter mapped from table <sys_base_menu_parameters>
type SysBaseMenuParameter struct {
	ID            int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	SysBaseMenuID *int64         `gorm:"column:sys_base_menu_id;type:bigint unsigned" json:"sys_base_menu_id"`
	Type          *string        `gorm:"column:type;type:varchar(191)" json:"type"`   // 地址栏携带参数为params还是query
	Key           *string        `gorm:"column:key;type:varchar(191)" json:"key"`     // 地址栏携带参数的key
	Value         *string        `gorm:"column:value;type:varchar(191)" json:"value"` // 地址栏携带参数的值
}

// TableName SysBaseMenuParameter's table name
func (*SysBaseMenuParameter) TableName() string {
	return TableNameSysBaseMenuParameter
}
