// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemHistoricaldict = "system_historicaldict"

// SystemHistoricaldict mapped from table <system_historicaldict>
type SystemHistoricaldict struct {
	ID                  int64     `gorm:"column:id;type:bigint;not null" json:"id"`
	CreateTime          time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
	UpdateTime          time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"`
	IsDeleted           int64     `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	Name                string    `gorm:"column:name;type:varchar(60);not null" json:"name"`
	Code                *string   `gorm:"column:code;type:varchar(30)" json:"code"`
	Description         *string   `gorm:"column:description;type:longtext" json:"description"`
	Sort                int64     `gorm:"column:sort;type:int;not null" json:"sort"`
	IsUsed              int64     `gorm:"column:is_used;type:tinyint(1);not null" json:"is_used"`
	HistoryID           int64     `gorm:"column:history_id;type:int;primaryKey;autoIncrement:true" json:"history_id"`
	HistoryDate         time.Time `gorm:"column:history_date;type:datetime(6);not null" json:"history_date"`
	HistoryChangeReason *string   `gorm:"column:history_change_reason;type:varchar(100)" json:"history_change_reason"`
	HistoryType         string    `gorm:"column:history_type;type:varchar(1);not null" json:"history_type"`
	HistoryUserID       *int64    `gorm:"column:history_user_id;type:bigint" json:"history_user_id"`
	ParentID            *int64    `gorm:"column:parent_id;type:bigint" json:"parent_id"`
	TypeID              *int64    `gorm:"column:type_id;type:bigint" json:"type_id"`
}

// TableName SystemHistoricaldict's table name
func (*SystemHistoricaldict) TableName() string {
	return TableNameSystemHistoricaldict
}
