// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAbpuserorganizationunit = "abpuserorganizationunits"

// Abpuserorganizationunit mapped from table <abpuserorganizationunits>
type Abpuserorganizationunit struct {
	ID                 int64     `gorm:"column:Id;type:bigint(20);primaryKey;autoIncrement:true" json:"Id"`
	CreationTime       time.Time `gorm:"column:CreationTime;type:datetime(6);not null" json:"CreationTime"`
	CreatorUserID      *int64    `gorm:"column:CreatorUserId;type:bigint(20)" json:"CreatorUserId"`
	TenantID           *int64    `gorm:"column:TenantId;type:int(11)" json:"TenantId"`
	UserID             int64     `gorm:"column:UserId;type:bigint(20);not null" json:"UserId"`
	OrganizationUnitID int64     `gorm:"column:OrganizationUnitId;type:bigint(20);not null" json:"OrganizationUnitId"`
	IsDeleted          []uint8   `gorm:"column:IsDeleted;type:bit(1);not null" json:"IsDeleted"`
}

// TableName Abpuserorganizationunit's table name
func (*Abpuserorganizationunit) TableName() string {
	return TableNameAbpuserorganizationunit
}
