// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLibitemoperateindexlog = "libitemoperateindexlog"

// Libitemoperateindexlog mapped from table <libitemoperateindexlog>
type Libitemoperateindexlog struct {
	ID                  string    `gorm:"column:Id;type:varchar(32);primaryKey" json:"Id"`
	CreationTime        time.Time `gorm:"column:CreationTime;type:datetime(6);not null" json:"CreationTime"`
	CreatorUserID       *int64    `gorm:"column:CreatorUserId;type:bigint(20)" json:"CreatorUserId"`
	CreatorUserName     *string   `gorm:"column:CreatorUserName;type:varchar(64)" json:"CreatorUserName"`
	ItemOperateType     int64     `gorm:"column:ItemOperateType;type:tinyint(3) ;not null" json:"ItemOperateType"`
	ItemOperateModeType int64     `gorm:"column:ItemOperateModeType;type:tinyint(3) ;not null" json:"ItemOperateModeType"`
	Remark              *string   `gorm:"column:Remark;type:varchar(256)" json:"Remark"`
	TenantID            int64     `gorm:"column:TenantId;type:int(11);not null" json:"TenantId"`
}

// TableName Libitemoperateindexlog's table name
func (*Libitemoperateindexlog) TableName() string {
	return TableNameLibitemoperateindexlog
}
