// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLibiteminventorylog = "libiteminventorylog"

// Libiteminventorylog mapped from table <libiteminventorylog>
type Libiteminventorylog struct {
	ID                string     `gorm:"column:Id;type:varchar(32);primaryKey" json:"Id"`
	CreationTime      time.Time  `gorm:"column:CreationTime;type:datetime(6);not null" json:"CreationTime"`
	CreatorUserID     *int64     `gorm:"column:CreatorUserId;type:bigint" json:"CreatorUserId"`
	LayerID           *string    `gorm:"column:LayerId;type:varchar(32)" json:"LayerId"`
	LayerName         *string    `gorm:"column:LayerName;type:varchar(32)" json:"LayerName"`
	ItemBarcode       string     `gorm:"column:ItemBarcode;type:varchar(32);not null" json:"ItemBarcode"`
	InventoryWorkType int64      `gorm:"column:InventoryWorkType;type:tinyint unsigned;not null" json:"InventoryWorkType"`
	InventoryState    int64      `gorm:"column:InventoryState;type:tinyint unsigned;not null" json:"InventoryState"`
	OffShelfTime      *time.Time `gorm:"column:OffShelfTime;type:datetime(6)" json:"OffShelfTime"`
	Remark            *string    `gorm:"column:Remark;type:varchar(256)" json:"Remark"`
	TenantID          int64      `gorm:"column:TenantId;type:int;not null" json:"TenantId"`
	InventoryWorkID   *string    `gorm:"column:InventoryWorkId;type:varchar(32)" json:"InventoryWorkId"`
	CreatorUserName   *string    `gorm:"column:CreatorUserName;type:varchar(64)" json:"CreatorUserName"`
	ItemCallNo        *string    `gorm:"column:ItemCallNo;type:varchar(64)" json:"ItemCallNo"`
	ItemTitle         *string    `gorm:"column:ItemTitle;type:varchar(256)" json:"ItemTitle"`
	LayerCode         *string    `gorm:"column:LayerCode;type:varchar(32)" json:"LayerCode"`
	LocationID        *string    `gorm:"column:LocationId;type:varchar(32)" json:"LocationId"`
	LocationName      *string    `gorm:"column:LocationName;type:varchar(128)" json:"LocationName"`
	LocLayerCode      *string    `gorm:"column:LocLayerCode;type:varchar(32)" json:"LocLayerCode"`
	LocLayerID        *string    `gorm:"column:LocLayerId;type:varchar(32)" json:"LocLayerId"`
	LocLayerName      *string    `gorm:"column:LocLayerName;type:varchar(32)" json:"LocLayerName"`
	ExceptionMsg      *string    `gorm:"column:ExceptionMsg;type:varchar(256)" json:"ExceptionMsg"`
	ItemAuthor        *string    `gorm:"column:ItemAuthor;type:varchar(256)" json:"ItemAuthor"`
	ItemISBN          *string    `gorm:"column:ItemISBN;type:varchar(32)" json:"ItemISBN"`
	ItemPublisher     *string    `gorm:"column:ItemPublisher;type:varchar(512)" json:"ItemPublisher"`
	OriginType        *int64     `gorm:"column:OriginType;type:tinyint unsigned" json:"OriginType"`
}

// TableName Libiteminventorylog's table name
func (*Libiteminventorylog) TableName() string {
	return TableNameLibiteminventorylog
}
