// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSyscoderule = "syscoderule"

// Syscoderule mapped from table <syscoderule>
type Syscoderule struct {
	ID                   string     `gorm:"column:Id;type:varchar(32);primaryKey" json:"Id"`
	CreationTime         time.Time  `gorm:"column:CreationTime;type:datetime(6);not null" json:"CreationTime"`
	CreatorUserID        *int64     `gorm:"column:CreatorUserId;type:bigint(20)" json:"CreatorUserId"`
	LastModificationTime *time.Time `gorm:"column:LastModificationTime;type:datetime(6)" json:"LastModificationTime"`
	LastModifierUserID   *int64     `gorm:"column:LastModifierUserId;type:bigint(20)" json:"LastModifierUserId"`
	IsDeleted            []uint8    `gorm:"column:IsDeleted;type:bit(1);not null" json:"IsDeleted"`
	DeleterUserID        *int64     `gorm:"column:DeleterUserId;type:bigint(20)" json:"DeleterUserId"`
	DeletionTime         *time.Time `gorm:"column:DeletionTime;type:datetime(6)" json:"DeletionTime"`
	Code                 *string    `gorm:"column:Code;type:varchar(32)" json:"Code"`
	Name                 *string    `gorm:"column:Name;type:varchar(64)" json:"Name"`
	CurrentNumber        *string    `gorm:"column:CurrentNumber;type:varchar(32)" json:"CurrentNumber"`
	RuleFormatJSON       *string    `gorm:"column:RuleFormatJson;type:text" json:"RuleFormatJson"`
	IsEnable             []uint8    `gorm:"column:IsEnable;type:bit(1);not null" json:"IsEnable"`
	Remark               *string    `gorm:"column:Remark;type:varchar(256)" json:"Remark"`
}

// TableName Syscoderule's table name
func (*Syscoderule) TableName() string {
	return TableNameSyscoderule
}
