definitions:
  request.AddBlackListInput:
    properties:
      ip:
        type: string
      unlock_time:
        description: 解锁时间，格式："yyyy-mm-dd hh:mm:ss"
        type: string
    type: object
  request.CreateLmsLogInput:
    properties:
      BrowserInfo:
        type: string
      ClientIpAddress:
        type: string
      ClientName:
        type: string
      CustomData:
        type: string
      Exception:
        type: string
      ExecutionDuration:
        type: integer
      ExecutionTime:
        type: string
      Id:
        type: integer
      ImpersonatorTenantId:
        type: integer
      ImpersonatorUserId:
        type: integer
      MethodName:
        type: string
      Parameters:
        type: string
      ReturnValue:
        type: string
      ServiceName:
        type: string
      TenantId:
        type: integer
      UserId:
        type: integer
    type: object
  request.ImportExcelByIndexInput:
    properties:
      author:
        default: -1
        description: 作者
        type: integer
      barcode:
        default: -1
        description: 条码号
        type: integer
      callNo:
        default: -1
        description: 索书号
        type: integer
      catalogCode:
        default: -1
        description: 分类号
        type: integer
      isbn:
        default: -1
        description: ISBN
        type: integer
      locationname:
        default: -1
        description: 当前馆藏地点
        type: integer
      pages:
        default: -1
        description: 页数
        type: integer
      path:
        default: d:/4.xlsx
        description: excel 服务器本地路径
        maxLength: 100
        minLength: 3
        type: string
      price:
        default: -1
        description: 单价
        type: integer
      pubDate:
        default: -1
        description: 出版日期
        type: integer
      publisher:
        default: -1
        description: 出版社
        type: integer
      tenantid:
        default: 1
        description: 租户
        maximum: 99999
        minimum: 1
        type: integer
      tid:
        default: -1
        description: tid
        type: integer
      title:
        default: -1
        description: 题名
        type: integer
    required:
    - path
    - tenantid
    type: object
  request.ImportExcelByNameInput:
    properties:
      author:
        default: 作者
        description: 作者
        type: string
      barcode:
        default: 条码号
        description: 条码号
        type: string
      callNo:
        default: 索书号
        description: 索书号
        type: string
      catalogCode:
        default: 分类号
        description: 分类号
        type: string
      isbn:
        default: ISBN
        description: ISBN
        type: string
      locationname:
        default: 当前馆藏地点
        description: 当前馆藏地点
        type: string
      pages:
        default: 页数
        description: 页数
        type: string
      path:
        default: d:/4.xlsx
        description: excel 服务器本地路径
        maxLength: 100
        minLength: 3
        type: string
      price:
        default: 单价
        description: 单价
        type: string
      pubDate:
        default: 出版日期
        description: 出版日期
        type: string
      publisher:
        default: 出版社
        description: 出版社
        type: string
      tenantid:
        default: 1
        description: 租户
        maximum: 99999
        minimum: 1
        type: integer
      tid:
        default: tid
        description: tid
        type: string
      title:
        default: 题名
        description: 题名
        type: string
    required:
    - path
    - tenantid
    type: object
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  request.RegisterRequest:
    properties:
      password:
        type: string
      role_id:
        type: integer
      username:
        type: string
    required:
    - password
    - role_id
    - username
    type: object
  request.UnLockIpInput:
    properties:
      ip:
        type: string
    type: object
  request.UpdateLmsLogInput:
    properties:
      BrowserInfo:
        type: string
      ClientIpAddress:
        type: string
      ClientName:
        type: string
      CustomData:
        type: string
      Exception:
        type: string
      ExecutionDuration:
        type: integer
      ExecutionTime:
        type: string
      Id:
        type: integer
      ImpersonatorTenantId:
        type: integer
      ImpersonatorUserId:
        type: integer
      MethodName:
        type: string
      Parameters:
        type: string
      ReturnValue:
        type: string
      ServiceName:
        type: string
      TenantId:
        type: integer
      UserId:
        type: integer
    type: object
  response.CreateLmsLogDto:
    type: object
  response.DeleteLmsLogDto:
    type: object
  response.ImportExcelDto:
    type: object
  response.QueryLmsDto:
    properties:
      items:
        description: 数据集
        items:
          $ref: '#/definitions/response.QueryLmsItem'
        type: array
      totalCount:
        description: 总数量
        type: integer
    type: object
  response.QueryLmsItem:
    properties:
      BrowserInfo:
        type: string
      ClientIpAddress:
        type: string
      ClientName:
        type: string
      CustomData:
        type: string
      Exception:
        type: string
      ExecutionDuration:
        type: integer
      ExecutionTime:
        type: string
      Id:
        type: integer
      ImpersonatorTenantId:
        type: integer
      ImpersonatorUserId:
        type: integer
      MethodName:
        type: string
      Parameters:
        type: string
      ReturnValue:
        type: string
      ServiceName:
        type: string
      TenantId:
        type: integer
      UserId:
        type: integer
    type: object
  response.UpdateLmsLogDto:
    type: object
  response.UploadResponse:
    properties:
      filePath:
        type: string
    type: object
  utils.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample API using Gin and Swagger.
  termsOfService: https://example.com/terms
  title: Swagger Example API
  version: "1.0"
paths:
  /IP/AddBlackList:
    post:
      consumes:
      - application/json
      description: 增加IP限制
      parameters:
      - description: 增加黑名单参数
        in: body
        name: AddBlackListInput
        required: true
        schema:
          $ref: '#/definitions/request.AddBlackListInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Invalid unlock time format
          schema:
            type: string
      summary: 增加IP限制
      tags:
      - IP
  /IP/UnLockIp:
    post:
      consumes:
      - application/json
      description: 解除IP限制
      parameters:
      - description: 解锁参数
        in: body
        name: UnLockIpInput
        required: true
        schema:
          $ref: '#/definitions/request.UnLockIpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: IP not found in the blacklist
          schema:
            type: string
      summary: 解除IP限制
      tags:
      - IP
  /api/services/app/Sysauditlmslog/CreateLmsLog:
    post:
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateLmsLogInput'
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.CreateLmsLogDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 新增LMS审计日志
      tags:
      - Sysauditlmslog
  /api/services/app/Sysauditlmslog/DeleteLmsLog:
    delete:
      parameters:
      - description: 根据主键删除
        in: query
        name: Id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回清单
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.DeleteLmsLogDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 查询LMS日志
      tags:
      - Sysauditlmslog
  /api/services/app/Sysauditlmslog/QueryLmsLog:
    get:
      parameters:
      - description: 最大执行时间
        in: query
        name: ExecutionDuration
        type: integer
      - description: 是否异常
        in: query
        name: IsException
        type: boolean
      - default: 100
        description: 获取多少条结果
        in: query
        maximum: 99999
        minimum: 1
        name: MaxResultCount
        type: integer
      - description: 方法
        in: query
        name: MethodName
        type: string
      - description: 参数
        in: query
        name: Parameters
        type: string
      - description: 服务名
        in: query
        name: ServiceName
        type: string
      - default: 0
        description: 跳过多少数量
        in: query
        maximum: 99999
        minimum: -1
        name: SkipCount
        type: integer
      - description: 租户
        in: query
        name: TenantId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回清单
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.QueryLmsDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 查询LMS日志
      tags:
      - Sysauditlmslog
  /api/services/app/Sysauditlmslog/UpdateLmsLog:
    put:
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateLmsLogInput'
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.UpdateLmsLogDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 修改LMS审计日志
      tags:
      - Sysauditlmslog
  /api/services/app/file/DownloadFile:
    get:
      consumes:
      - application/json
      description: 根据文件路径下载文件
      parameters:
      - description: 文件路径
        in: query
        name: filePath
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: 文件下载成功
          schema:
            type: file
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "404":
          description: 文件未找到
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 下载文件
      tags:
      - File
  /api/services/app/file/UploadFile:
    post:
      consumes:
      - multipart/form-data
      description: 接收一个文件和对象信息
      parameters:
      - description: 文件名称
        in: formData
        name: name
        required: true
        type: string
      - description: 文件描述
        in: formData
        name: description
        type: string
      - description: 文件描述
        in: formData
        name: cover
        type: boolean
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 上传成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UploadResponse'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 上传文件
      tags:
      - File
  /api/services/app/libitem/ImportExcelByIndex:
    post:
      consumes:
      - application/json
      description: 通过提供的Excel文件导入图书信息
      parameters:
      - description: 导入参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ImportExcelByIndexInput'
      produces:
      - application/json
      responses:
        "200":
          description: 导入成功，返回导入的数据
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ImportExcelDto'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 导入图书信息
      tags:
      - libitems
  /api/services/app/libitem/ImportExcelByName:
    post:
      consumes:
      - application/json
      description: 通过提供的Excel文件导入图书信息
      parameters:
      - description: 导入参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ImportExcelByNameInput'
      produces:
      - application/json
      responses:
        "200":
          description: 导入成功，返回导入的数据
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ImportExcelDto'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 导入图书信息
      tags:
      - libitems
  /auth/DebugIn:
    get:
      consumes:
      - application/json
      description: 本地调试写入token
      parameters:
      - in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: token input success
          schema:
            type: string
      summary: 本地调试写入token
      tags:
      - Debug
  /auth/DebugOut:
    get:
      consumes:
      - application/json
      description: 本地调试注销token
      produces:
      - application/json
      responses:
        "200":
          description: token clear success
          schema:
            type: string
      summary: 本地调试注销token
      tags:
      - Debug
  /auth/Login:
    post:
      consumes:
      - application/json
      description: 用户输入用户名和密码，验证通过后返回JWT Token。
      parameters:
      - description: 用户登录请求
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "401":
          description: Invalid username or password
          schema:
            type: string
      summary: 用户登录
      tags:
      - Auth
  /auth/LoginOut:
    post:
      consumes:
      - application/json
      description: 注销token
      produces:
      - application/json
      responses:
        "200":
          description: User logout successfully
          schema:
            type: string
      summary: 注销token
      tags:
      - Auth
  /auth/Register:
    post:
      consumes:
      - application/json
      description: 用户提交注册信息，注册成功后返回成功消息。
      parameters:
      - description: 用户注册请求
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "409":
          description: Username already exists
          schema:
            type: string
      summary: 用户注册
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    description: JWT Authorization header (Bearer token)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
