definitions:
  models.Order:
    description: 订单数据模型
    properties:
      amount:
        example: 100.5
        type: number
      customer:
        example: John Doe
        type: string
      id:
        description: '@ID'
        type: integer
    type: object
  request.UserRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  response.CommonResponse:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回的数据，可以是任何类型
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: 获取所有订单信息
      produces:
      - application/json
      responses:
        "200":
          description: 订单列表
          schema:
            $ref: '#/definitions/response.CommonResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 获取所有订单
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: 创建新的订单并返回订单信息
      parameters:
      - description: 订单信息
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "201":
          description: 成功创建的订单信息
          schema:
            $ref: '#/definitions/response.CommonResponse'
        "400":
          description: 无效的请求
          schema:
            $ref: '#/definitions/response.CommonResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 创建订单
      tags:
      - orders
  /users:
    get:
      consumes:
      - application/json
      description: 获取所有用户信息
      produces:
      - application/json
      responses:
        "200":
          description: 获取到的所有用户列表
          schema:
            $ref: '#/definitions/response.CommonResponse'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 获取所有用户
      tags:
      - users
    post:
      consumes:
      - application/json
      description: 创建一个新的用户并返回用户信息
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功创建的用户信息
          schema:
            $ref: '#/definitions/response.CommonResponse'
        "400":
          description: 无效的输入
          schema:
            $ref: '#/definitions/response.CommonResponse'
        "500":
          description: 创建用户失败
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 创建新用户
      tags:
      - users
swagger: "2.0"
