definitions:
  models.TestOrder:
    description: 订单数据模型
    properties:
      amount:
        example: 100.5
        type: number
      customer:
        example: John Doe
        type: string
      id:
        description: '@ID'
        type: integer
    type: object
  request.CreateLmsLogInput:
    properties:
      BrowserInfo:
        type: string
      ClientIpAddress:
        type: string
      ClientName:
        type: string
      CustomData:
        type: string
      Exception:
        type: string
      ExecutionDuration:
        type: integer
      ExecutionTime:
        type: string
      Id:
        type: integer
      ImpersonatorTenantId:
        type: integer
      ImpersonatorUserId:
        type: integer
      MethodName:
        type: string
      Parameters:
        type: string
      ReturnValue:
        type: string
      ServiceName:
        type: string
      TenantId:
        type: integer
      UserId:
        type: integer
    type: object
  request.ImportExcelInput:
    properties:
      author:
        default: 作者
        description: 作者
        type: string
      barcode:
        default: 条码号
        description: 条码号
        type: string
      callNo:
        default: 索书号
        description: 索书号
        type: string
      catalogCode:
        default: 分类号
        description: 分类号
        type: string
      isbn:
        default: ISBN
        description: ISBN
        type: string
      locationname:
        default: 当前馆藏地点
        description: 当前馆藏地点
        type: string
      pages:
        default: 页数
        description: 页数
        type: string
      path:
        default: d:/4.xlsx
        description: excel 服务器本地路径
        maxLength: 100
        minLength: 3
        type: string
      price:
        default: 单价
        description: 单价
        type: string
      pubDate:
        default: 出版日期
        description: 出版日期
        type: string
      publisher:
        default: 出版社
        description: 出版社
        type: string
      tenantid:
        default: 1
        description: 租户
        maximum: 99999
        minimum: 1
        type: integer
      tid:
        default: tid
        description: tid
        type: string
      title:
        default: 题名
        description: 题名
        type: string
    required:
    - path
    - tenantid
    type: object
  request.UpdateLmsLogInput:
    properties:
      BrowserInfo:
        type: string
      ClientIpAddress:
        type: string
      ClientName:
        type: string
      CustomData:
        type: string
      Exception:
        type: string
      ExecutionDuration:
        type: integer
      ExecutionTime:
        type: string
      Id:
        type: integer
      ImpersonatorTenantId:
        type: integer
      ImpersonatorUserId:
        type: integer
      MethodName:
        type: string
      Parameters:
        type: string
      ReturnValue:
        type: string
      ServiceName:
        type: string
      TenantId:
        type: integer
      UserId:
        type: integer
    type: object
  request.UserRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  response.CreateLmsLogDto:
    type: object
  response.DeleteLmsLogDto:
    type: object
  response.ImportExcelDto:
    type: object
  response.QueryLmsDto:
    properties:
      items:
        description: 数据集
        items:
          $ref: '#/definitions/response.QueryLmsItem'
        type: array
      totalCount:
        description: 总数量
        type: integer
    type: object
  response.QueryLmsItem:
    properties:
      BrowserInfo:
        type: string
      ClientIpAddress:
        type: string
      ClientName:
        type: string
      CustomData:
        type: string
      Exception:
        type: string
      ExecutionDuration:
        type: integer
      ExecutionTime:
        type: string
      Id:
        type: integer
      ImpersonatorTenantId:
        type: integer
      ImpersonatorUserId:
        type: integer
      MethodName:
        type: string
      Parameters:
        type: string
      ReturnValue:
        type: string
      ServiceName:
        type: string
      TenantId:
        type: integer
      UserId:
        type: integer
    type: object
  response.UpdateLmsLogDto:
    type: object
  response.UploadResponse:
    properties:
      filePath:
        type: string
    type: object
  response.UserDto:
    properties:
      id:
        description: 用户ID
        type: integer
      name:
        description: 用户名
        type: string
    type: object
  utils.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/services/app/Sysauditlmslog/CreateLmsLog:
    post:
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateLmsLogInput'
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.CreateLmsLogDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 新增LMS审计日志
      tags:
      - Sysauditlmslog
  /api/services/app/Sysauditlmslog/DeleteLmsLog:
    delete:
      parameters:
      - description: 根据主键删除
        in: query
        name: Id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回清单
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.DeleteLmsLogDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 查询LMS日志
      tags:
      - Sysauditlmslog
  /api/services/app/Sysauditlmslog/QueryLmsLog:
    get:
      parameters:
      - description: 最大执行时间
        in: query
        name: ExecutionDuration
        type: integer
      - description: 是否异常
        in: query
        name: IsException
        type: boolean
      - default: 100
        description: 获取多少条结果
        in: query
        maximum: 99999
        minimum: 1
        name: MaxResultCount
        type: integer
      - description: 方法
        in: query
        name: MethodName
        type: string
      - description: 参数
        in: query
        name: Parameters
        type: string
      - description: 服务名
        in: query
        name: ServiceName
        type: string
      - default: 0
        description: 跳过多少数量
        in: query
        maximum: 99999
        minimum: -1
        name: SkipCount
        type: integer
      - description: 租户
        in: query
        name: TenantId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回清单
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.QueryLmsDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 查询LMS日志
      tags:
      - Sysauditlmslog
  /api/services/app/Sysauditlmslog/UpdateLmsLog:
    put:
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateLmsLogInput'
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.UpdateLmsLogDto'
                  type: array
                msg:
                  type: string
              type: object
      summary: 修改LMS审计日志
      tags:
      - Sysauditlmslog
  /api/services/app/file/UploadFile:
    post:
      consumes:
      - multipart/form-data
      description: 接收一个文件和对象信息
      parameters:
      - description: 文件名称
        in: formData
        name: name
        required: true
        type: string
      - description: 文件描述
        in: formData
        name: description
        type: string
      - description: 文件描述
        in: formData
        name: cover
        type: boolean
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 上传成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UploadResponse'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 上传文件
      tags:
      - File
  /api/services/app/libitem/ImportExcel:
    post:
      consumes:
      - application/json
      description: 通过提供的Excel文件导入图书信息
      parameters:
      - description: 导入参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ImportExcelInput'
      produces:
      - application/json
      responses:
        "200":
          description: 导入成功，返回导入的数据
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ImportExcelDto'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 导入图书信息
      tags:
      - libitems
  /api/services/app/order/CreateOrder:
    post:
      consumes:
      - application/json
      description: 创建新的订单并返回订单信息
      parameters:
      - description: 订单信息
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.TestOrder'
      produces:
      - application/json
      responses:
        "201":
          description: 成功创建的订单信息
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.TestOrder'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的请求
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 创建订单
      tags:
      - orders
  /api/services/app/order/GetOrders:
    get:
      consumes:
      - application/json
      description: 获取所有订单信息
      produces:
      - application/json
      responses:
        "200":
          description: 订单列表
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.TestOrder'
                  type: array
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取所有订单
      tags:
      - orders
  /api/services/app/user/CreateUser:
    post:
      consumes:
      - application/json
      description: 创建一个新的用户并返回用户信息
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功创建的用户信息
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserDto'
                msg:
                  type: string
              type: object
        "400":
          description: 无效的输入
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 创建用户失败
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 创建新用户
      tags:
      - users
  /api/services/app/user/GetUsers:
    get:
      consumes:
      - application/json
      description: 获取所有用户信息
      produces:
      - application/json
      responses:
        "200":
          description: 获取到的所有用户列表
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.UserDto'
                  type: array
                msg:
                  type: string
              type: object
        "500":
          description: 内部服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取所有用户
      tags:
      - users
swagger: "2.0"
