// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameLibailibrarainbaseinfoitem = "libailibrarainbaseinfoitem"

// Libailibrarainbaseinfoitem mapped from table <libailibrarainbaseinfoitem>
type Libailibrarainbaseinfoitem struct {
	ID         int64  `gorm:"column:Id;type:bigint;primaryKey;autoIncrement:true" json:"Id"`
	Name       string `gorm:"column:Name;type:varchar(50);not null" json:"Name"`
	Content    string `gorm:"column:Content;type:varchar(1024);not null" json:"Content"`
	BaseInfoID int64  `gorm:"column:BaseInfoId;type:bigint;not null" json:"BaseInfoId"`
}

// TableName Libailibrarainbaseinfoitem's table name
func (*Libailibrarainbaseinfoitem) TableName() string {
	return TableNameLibailibrarainbaseinfoitem
}
